version: '3.5'

services:
    backend:
        image: backend
        build: ./backend-example-docker-master
        ports: 
            - 8000:8000
        environment:
            - REDIS=redis
            - DB_USERNAME=user
            - DB_PASSWORD=example
            - DB_HOST=db
            
        depends_on:
            - db
        
        
    frontend:
        image: frontend
        build: ./frontend-example-docker-master
        ports: 
            - 5000:5000

    redis:
        image: redis
        
    db:
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: example
            POSTGRES_USER: user