version: '3.5'

services:
    backend:
        image: backend
        build: ./backend-example-docker-master
        ports: 
            - 8000:8000
        environment:
            - REDIS=redis
        
        
    frontend:
        image: frontend
        build: ./frontend-example-docker-master
        ports: 
            - 5000:5000

    redis:
        image: redis